extends:
  - 'eslint-config-wikimedia/server'

env:
  browser: true

rules:
  camelcase:
    - error
    - properties: never
  indent:
    - off
    - 4
  no-underscore-dangle:
    - off
  no-unused-vars:
    - error
    - args: none
  space-in-parens:
    - error
    - never
  # defined in WM config to avoid breaking IE. Not needed here
  no-restricted-syntax:
    - off
  array-bracket-spacing:
    - off
  computed-property-spacing:
    - off
  arrow-parens:
    - off
  no-multi-spaces:
    - off

